### ISSUE TITLE
Semi-impersonation via unreadable characters

### ISSUE THREAD

**Issue by addi-sp-sp-4** [maximforever/dictionary#11]
You can personate everybody by registering a new account with a character that does not get displayed.

[As you can see here, you can create an account called "max"](https://www.hackterms.com/impersonation)

Luckily there is no parsing differential in the database, so I can not escalate this to spoof an admin account.

**Comment by maximforever** [comment]
Thank you for raising this - your comments are giving me a crash course on security, and I have a lot to learn! Please let me know if you find anything else, if there are any resources you'd recommend, and feel free to email me directly at hello@hackterms.com

**Comment by maximforever** [comment]
I _think_ I resolved this but restricting the character set for usernames to alphanumeric latin chars.
