### ISSUE TITLE
(Feature request) requested definition 

### ISSUE THREAD

**Issue by IdiosApps** [maximforever/dictionary#15]
This could be user-built, or made in bulk. May help add content quickly.

**Comment by maximforever** [comment]
Thanks for the request! Could you clarify a little bit? There's a "top requested definitions" tab on the home page that keeps track of every searched term without any definitions. What kind of a feature are you imagining?

**Comment by IdiosApps** [comment]
Woah, perfect. Better implementation than I was thinking about! 
I just didn't see that button on the homepage. Can safely close this issue haha.
