### ISSUE TITLE
Add new Term

### ISSUE THREAD

**Issue by KBPsystem777** [maximforever/dictionary#2]
Users should be able to add new `terminology`. Right now, the only way to create new `terminology` is adding a related `tag` or `keyword` on the parent `terminology`

**Comment by maximforever** [comment]
Thank you for taking the time to comment! Could you clarify? `Terms` (ex: javascript) have multiple `definitions` (ex: "a popular language"), and are created automatically when you add a new `definition`. There's no point of adding a new `term` without any definitions

**Comment by KBPsystem777** [comment]
For example, I want to create a definition for `create-react-app` which is currently not available on the database, where am I supposed to enter that?

**Comment by maximforever** [comment]
@KBPsystem777 you can create a definition for any term by hitting the "Don't see a good definition? Add your own!" prompt that pops up when you search for anything. So:

1. Search for `create-react-app`
2. There are no results, so the "There are no definitions for create-react-app. Want to add one?" message pops up
3. Click it, and you get a new-definition form

Let me know if this makes sense/isn't intuitive!

**Comment by KBPsystem777** [comment]
Oh yeah, saw it. Never tried to type on search bar and see the result. Well I think that will do for now :)
