### ISSUE TITLE
Trending and Most requested should be marked up as tabs

### ISSUE THREAD

**Issue by garcialo** [maximforever/dictionary#24]
Expectation: User should be able to navigate to and activate Trending and Most requested with keyboard.
Expectation: Trending and Most requested must be identifiable as tabs when using a screen reader.

Actual Behavior: Trending and Most requested are not reachable/activateable with keyboard alone.

Would advise following this pattern.
http://ebay.github.io/mindpatterns/disclosure/tabs/index.html

**Comment by maximforever** [comment]
@garcialo - great idea; this is now live!
